---
- name: Установка yc cli (для работы с S3)
  shell: |
    curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    #source ~/.bashrc
  become_user: "{{ admin_user }}"

- name: Копируем ключ сервисного аккаунта для авторизации yc
  copy:
    src: sa_key.json
    dest: "/home/{{ admin_user }}/.yc-sa-key.json"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0600'

- name: Настройка профиля yc
  shell: |
    /home/{{ admin_user }}/yandex-cloud/bin/yc config profile create mediawiki-sa || true
    /home/{{ admin_user }}/yandex-cloud/bin/yc config set service-account-key /home/{{ admin_user }}/.yc-sa-key.json
    /home/{{ admin_user }}/yandex-cloud/bin/yc config set cloud-id {{ yandex_cloud_id }}
    /home/{{ admin_user }}/yandex-cloud/bin/yc config set folder-id {{ yandex_folder_id }}
  become_user: "{{ admin_user }}"

- name: Установка AWS CLI (для работы с S3)
  pip:
    name: awscli
    state: present
  become: yes

- name: Создание директории .aws
  file:
    path: /home/{{ admin_user }}/.aws
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0700'

- name: Настройка скрипта эфемерного ключа для Yandex Object Storage
  template:
    src: issue-ephemeral-script.sh.j2
    dest: /home/{{ admin_user }}/.aws/issue-ephemeral-script.sh
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0700'

- name: Настройка AWS config
  template:
    src: aws_config.j2
    dest: /home/{{ admin_user }}/.aws/config
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0600'

- name: Настройка учетных данных AWS
  template:
    src: aws_credentials.j2
    dest: /home/{{ admin_user }}/.aws/credentials
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0600'

- name: Создание бэкап скрипта
  template:
    src: backup.sh.j2
    dest: /usr/local/bin/backup_mediawiki_db.sh
    owner: root
    group: root
    mode: '0755'

- name: Создание локальной директории для временного хранения бэкапов
  file:
    path: /var/backups/mediawiki
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0750'

- name: Добавляем cron задачу на ежедневный бэкап БД
  cron:
    name: "MediaWiki PostgreSQL daily backup"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/backup_mediawiki_db.sh >> /var/log/mediawiki_backup.log 2>&1"
    user: "{{ admin_user }}"

- name: Настройка логирования для бэкапов
  copy:
    dest: /etc/logrotate.d/mediawiki-backup
    content: |
      /var/log/mediawiki_backup.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          create 0640 root root
      }