- name: Добавляем репозиторий Ondrej PHP
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes

- name: Установка Nginx + php
  apt:
    name:
      - nginx
      - php8.3-fpm
      - php8.3-mbstring
      - php8.3-gd
      - php8.3-xml
      - php8.3-bcmath
      - php8.3-pgsql
    state: present

- name: Настройка параметров PHP для Zabbix
  lineinfile:
    path: "/etc/php/8.3/fpm/php.ini"
    regexp: "^{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
  loop:
    - { key: 'post_max_size', value: '16M' }
    - { key: 'max_execution_time', value: '300' }
    - { key: 'max_input_time', value: '300' }
  notify: restart php-fpm

- name: Права на директорию сессий PHP
  file:
    path: /var/lib/php/sessions
    state: directory
    owner: www-data
    group: www-data
    mode: '0777'

- name: Перезапуск PHP
  service:
    name: php8.3-fpm
    state: restarted

- name: Удалить стандартный default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Настроить upstream и proxy_pass
  template:
    src: lb-mediawiki.conf.j2
    dest: /etc/nginx/sites-available/mediawiki-lb
  notify: restart nginx

- name: Настройка TCP-проксирования для PostgreSQL
  blockinfile:
    path: /etc/nginx/nginx.conf
    block: |
      stream {
          upstream postgres_backend {
              server {{ hostvars['db_master']['internal_ip'] }}:5432 max_fails=2 fail_timeout=10s;
              server {{ hostvars['db_replica']['internal_ip'] }}:5432 backup;
          }
      
          server {
              listen 5432;
              proxy_pass postgres_backend;
              proxy_connect_timeout 2s;
              proxy_timeout 30s;
          }
      }
  notify: restart nginx

- name: Включить сайт
  file:
    src: /etc/nginx/sites-available/mediawiki-lb
    dest: /etc/nginx/sites-enabled/mediawiki-lb
    state: link
  notify: restart nginx