- name: Добавляем репозиторий Ondrej PHP
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes

- name: Установка Nginx, PHP и необходимых модулей
  apt:
    name:
      - php8.3-fpm
      - php8.3-cli
      - php8.3-pgsql
      - php8.3-mbstring
      - php8.3-intl
      - php8.3-xml
      - php8.3-curl
      - php8.3-zip
      - php8.3-gd
      - composer
      - nginx
    state: present
  register: apt_result
  until: apt_result is success
  retries: 10
  delay: 30

- name: Скачать MediaWiki
  get_url:
    url: "https://releases.wikimedia.org/mediawiki/{{ mw_version[:4] }}/mediawiki-{{ mw_version }}.tar.gz"
    dest: "/tmp/mediawiki.tar.gz"

- name: Убеждаемся, что директория MediaWiki существует
  file:
    path: "{{ mw_install_dir | dirname }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Распаковать в каталог приложения
  unarchive:
    src: "/tmp/mediawiki.tar.gz"
    dest: "{{ mw_install_dir | dirname }}"
    remote_src: yes
    owner: www-data
    group: www-data
    extra_opts: [--strip-components=1] # Удаляем верхний уровень, чтобы содержимое попало прямо в /var/www/mediawiki
    creates: "{{ mw_install_dir }}/index.php"

- name: Установка расширения AWS (S3)
  git:
    repo: "https://gerrit.wikimedia.org/r/mediawiki/extensions/AWS"
    dest: "{{ mw_install_dir }}/extensions/AWS"
    version: "master"

- name: Установка aws-sdk-php через composer
  composer:
    command: require
    arguments: "aws/aws-sdk-php"
    working_dir: "{{ mw_install_dir }}"

- name: Создать каталог для логов
  file:
    path: /var/log/mediawiki
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Сгенерировать LocalSettings.php из шаблона
  template:
    src: LocalSettings.php.j2
    dest: "{{ mw_install_dir }}/LocalSettings.php"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Настройка PHP-FPM пула для MediaWiki
  template:
    src: www-mediawiki.conf.j2
    dest: /etc/php/8.3/fpm/pool.d/mediawiki.conf
  notify: restart php-fpm

- name: Настройка Nginx виртуального хоста для MediaWiki (на app серверах, для статики)
  template:
    src: mediawiki-app-nginx.conf.j2
    dest: /etc/nginx/sites-available/mediawiki
  notify: restart nginx